name: Backend CI/CD Pipeline (Simple Deploy)

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run tests
        run: go test ./...
        working-directory: backend

      - name: Build binary
        run: go build -o app .
        working-directory: backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy to EC2 (simple SSH deploy)
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

          scp -o StrictHostKeyChecking=no -i key.pem backend/app ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/app

          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            pkill app || true
            nohup ./app > app.log 2>&1 &
          EOF
          
          permissions:
  id-token: write
  contents: read